spring:
  datasource:
    url: jdbc:h2:tcp://localhost/D:/h2db/blog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true  # 쿼리 확인용
        default_batch_fetch_size: 10
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace